---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','Updates', 'DefinitionUpdates']
      register: result

    # output results
    - debug: var=result
    
    # reboot only if required
    - win_reboot:
      when: result.reboot_required
      
      # Send Email
    
  - name: Send a success email
  mail:
   host: smtp.office365.com
   port: 587 
   username: migrationtesting@mouritech.com
   password: 700G12e315m
   to: Ramanjaneyulu BUTHARAJU<ramanjaneyulub.in@mouritech.com>
   subject: Installation Update
   body: 'Attached is the report of the changes that is live'
  
